import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { ProjectEnvContextProvider } from '../contexts/ProjectEnvContextProvider'
import { OpenAIKeyProvider } from '../contexts/OpenAIContextProvider'
import { DeepgramContextProvider } from '../contexts/DeepgramContextProvider'
import { Toaster } from '@/components/ui/toaster'
import { AuthProvider } from '@/contexts/auth-context'
import { ProtectedRoute } from '@/components/auth/protected-route'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <ProjectEnvContextProvider>
            <OpenAIKeyProvider>
              <DeepgramContextProvider>
                <ProtectedRoute>
                  {children}
                </ProtectedRoute>
                <Toaster />
              </DeepgramContextProvider>
            </OpenAIKeyProvider>
          </ProjectEnvContextProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
